### ISSUE TITLE
update and delete do not work

### ISSUE THREAD

**Issue by dleute** [dtoubelis/sails-cassandra3#4]
I have models that all have a default attribute of name, nothing else.

```
module.exports.models = {

  attributes: {
    name: {
      type: 'string'
    }
  }
...
}
```

All the controllers are default generated.

/model/create?name=whatever works fine.

/model lists all objects for the model.

/model/update/[uuid]?name=foo throws this error:

```
error: Sending 500 ("Server Error") response: 
 Error (E_UNKNOWN) :: Encountered an unexpected error
: PRIMARY KEY part id found in SET part
    at ResponseError.DriverError (/Users/dleute/Documents/IBM/dbApi/node_modules/sails-cassandra3/node_modules/cassandra-driver/lib/errors.js:14:19)
    at new ResponseError (/Users/dleute/Documents/IBM/dbApi/node_modules/sails-cassandra3/node_modules/cassandra-driver/lib/errors.js:51:24)
    at FrameReader.readError (/Users/dleute/Documents/IBM/dbApi/node_modules/sails-cassandra3/node_modules/cassandra-driver/lib/readers.js:316:13)
    at Parser.parseBody (/Users/dleute/Documents/IBM/dbApi/node_modules/sails-cassandra3/node_modules/cassandra-driver/lib/streams.js:189:66)
    at Parser._transform (/Users/dleute/Documents/IBM/dbApi/node_modules/sails-cassandra3/node_modules/cassandra-driver/lib/streams.js:137:10)
    at Parser.Transform._read (_stream_transform.js:167:10)
    at Parser.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:300:12)
    at writeOrBuffer (_stream_writable.js:286:5)
    at Parser.Writable.write (_stream_writable.js:214:11)
    at Protocol.ondata (_stream_readable.js:542:20)
    at emitOne (events.js:77:13)
    at Protocol.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Protocol.Readable.push (_stream_readable.js:111:10)
    at Protocol.Transform.push (_stream_transform.js:128:32)
    at Protocol.readItems (/Users/dleute/Documents/IBM/dbApi/node_modules/sails-cassandra3/node_modules/cassandra-driver/lib/streams.js:109:10)
    at Protocol._transform (/Users/dleute/Documents/IBM/dbApi/node_modules/sails-cassandra3/node_modules/cassandra-driver/lib/streams.js:32:10)
    at Protocol.Transform._read (_stream_transform.js:167:10)
    at Protocol.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:300:12)
    at writeOrBuffer (_stream_writable.js:286:5)

Details:  ResponseError: PRIMARY KEY part id found in SET part
```

/model/update/[id]?name=foo works when backed by mysql or disk db.

Also, I think models are being created by the safari thing where it checks a url to preview content before you actually say to load it. That's annoying. But not the frameworks fault (basically all creates are executed twice when using safari. Stupid).

I am trying to learn about these adapters as I have a clever idea that may save me time, but I haven't gotten far enough along to diagnose these problems.

Thanks!

--Derrek

**Comment by dtoubelis** [comment]
You need to define primary key. Unlike with relational databases, indices and keys are not optional woth cassandra. Here is an example of a proper model definition:

```
  attributes: {
    id: {type: 'string', primaryKey: true, autoIncrement: true},
    name: {type: 'string', required: true}
  }```

**Comment by dleute** [comment]
Ah. I didn't define the id field. It is the automatic id field generated by the model. (in fact, I don't know what set it up since it's not in the model or models.js).

As such I thought it would do the right thing automatically. So models work right out of the box as they do with other DB's.

Shouldn't that definition be the default definition for all auto increment id fields that come with the generator? With MySQL the id field is automatically auto increment and primary key without me doing anything. (I just checked in my DB)

Is this intended to work differently than mysql?

--Derrek

**Comment by dtoubelis** [comment]
Waterline was designed around mysql and some concept simply do not translate to other databases the same way. For instance `autoIncrement` property enforces field type be integer, however `autoincrement` in cassandra means just create a new UUID and UUIDs are strings. I submitted a [request for improvement](https://github.com/balderdashy/waterline/issues/909) to waterline but sails/waterline a slowly dying projects, so nobody cares.

**Comment by dleute** [comment]
I understand. It's not a problem to define it. I just didn't know I needed to.

If they are slowly dying, did something better/different replace them?

I'm looking for a simple way to bind database models to an api. Exactly what sails/waterline does.

**Comment by dtoubelis** [comment]
You should look for an ORM/ODM specifically for Cassandra. I myself not aware of any but I haven't been using Cassandra for at least 2 years, so there may be some new development.

I would particularly advise against using generic ORM frameworks like Waterline for NoSQL databases. The reason is that you get the smallest common denominator of functionality between all databases essentially crippling Cassandra to a small subset of SQL functionality and loosing all the awesomeness.

If I ever need to work with Cassandra again I would probably go with `cassandra-driver` directly. And if I have choice of database I would go with `rethinkdb` or `mongo` :-)
